### ISSUE TITLE
TitleBarCtrls +DataBase

### ISSUE THREAD

**Issue by limelect** [fpiette/OvbImgOrganizer#1]
D10.2.3
1.Which component I have to get for TitleBarCtrls
2. want it to be better to search for pictures in a directory

**Comment by fpiette** [comment]
TitleBarCtrls is a built in Delphi component. You need Delphi 10.4.1 for that. You can replace it with TMainMenu instead, you'll get a classic main menu instead of a menu in title bar. Upgrade to latest Delphi.

**Comment by limelect** [comment]
Thanks
