### ISSUE TITLE
Unit Winapi.D2D1_1

### ISSUE THREAD

**Issue by spawn451** [fpiette/OvbImgOrganizer#2]
Hello, I'm trying to use your Winapi.D2D1_1 unit but these are missing : Winapi.D2D1EffectAuthor, Winapi.DCommon,Winapi.DocumentTarget. Can you help me ?

**Comment by fpiette** [comment]
I added the units Winapi.D2D1EffectAuthor, Winapi.DCommon, Winapi.DocumentTarget.

**Comment by spawn451** [comment]
Thanks :-)
